version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT


  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d


  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: services/api-service/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - redis
      - postgres

  feed-service:
    container_name: feed-service
    build:
      context: .
      dockerfile: services/feed-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - kafka
      - redis
      - postgres

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - redis
      - postgres
