apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-system-config
data:
  PORT: "3000"
  NOTIFICATION_PORT: "3001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "feedsystem"
  JWT_EXPIRES_IN: "7d"
  KAFKA_BROKER: "kafka:9092"
  KAFKAJS_NO_PARTITIONER_WARNING: "1"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
